In [1]:
import csv

sp500 = []

with open('sp500/S&P 500 Historical Components & Changes(08-17-2024).csv', 'r') as input:
    reader = csv.reader(input)
    latest = list(reader)[-1][-1]
    # yahoo finance uses - instead of . in symbol names
    sp500 = [name.replace('.', '-') for name in latest.split(',')]

print(len(sp500))

503

In [2]:
import yfinance as yf

df = yf.download("SPY AAPL", period="1mo")
df

[*********************100%***********************]  2 of 2 completed

Price                       Adj Close                   Close              \
Ticker                           AAPL         SPY        AAPL         SPY
Date
2024-09-30 00:00:00+00:00  233.000000  573.760010  233.000000  573.760010
2024-10-01 00:00:00+00:00  226.210007  568.619995  226.210007  568.619995
2024-10-02 00:00:00+00:00  226.779999  568.859985  226.779999  568.859985
2024-10-03 00:00:00+00:00  225.669998  567.820007  225.669998  567.820007
2024-10-04 00:00:00+00:00  226.800003  572.979980  226.800003  572.979980
2024-10-07 00:00:00+00:00  221.690002  567.799988  221.690002  567.799988
2024-10-08 00:00:00+00:00  225.770004  573.169983  225.770004  573.169983
2024-10-09 00:00:00+00:00  229.539993  577.140015  229.539993  577.140015
2024-10-10 00:00:00+00:00  229.039993  576.130005  229.039993  576.130005
2024-10-11 00:00:00+00:00  227.550003  579.580017  227.550003  579.580017
2024-10-14 00:00:00+00:00  231.300003  584.320007  231.300003  584.320007
2024-10-15 00:00:00+00:00  233.850006  579.780029  233.850006  579.780029
2024-10-16 00:00:00+00:00  231.779999  582.299988  231.779999  582.299988
2024-10-17 00:00:00+00:00  232.149994  582.349976  232.149994  582.349976
2024-10-18 00:00:00+00:00  235.000000  584.590027  235.000000  584.590027
2024-10-21 00:00:00+00:00  236.479996  583.630005  236.479996  583.630005
2024-10-22 00:00:00+00:00  235.860001  583.320007  235.860001  583.320007
2024-10-23 00:00:00+00:00  230.759995  577.989990  230.759995  577.989990
2024-10-24 00:00:00+00:00  230.570007  579.239990  230.570007  579.239990
2024-10-25 00:00:00+00:00  231.410004  579.039978  231.410004  579.039978
2024-10-28 00:00:00+00:00  233.399994  580.830017  233.399994  580.830017
2024-10-29 00:00:00+00:00  233.669998  581.770020  233.669998  581.770020
2024-10-30 00:00:00+00:00  230.100006  580.010010  230.100006  580.010010
2024-10-31 00:00:00+00:00  227.354996  571.349976  227.354996  571.349976

Price                            High                     Low              \
Ticker                           AAPL         SPY        AAPL         SPY
Date
2024-09-30 00:00:00+00:00  233.000000  574.380005  229.649994  568.080017
2024-10-01 00:00:00+00:00  229.649994  574.059998  223.740005  566.000000
2024-10-02 00:00:00+00:00  227.369995  569.900024  223.020004  565.270020
2024-10-03 00:00:00+00:00  226.809998  569.799988  223.320007  565.489990
2024-10-04 00:00:00+00:00  228.000000  573.359985  224.130005  568.099976
2024-10-07 00:00:00+00:00  225.690002  571.960022  221.330002  566.630005
2024-10-08 00:00:00+00:00  225.979996  573.780029  223.250000  569.530029
2024-10-09 00:00:00+00:00  229.750000  577.710022  224.830002  572.549988
2024-10-10 00:00:00+00:00  229.500000  577.580017  227.169998  574.489990
2024-10-11 00:00:00+00:00  229.410004  580.330017  227.339996  575.909973
2024-10-14 00:00:00+00:00  231.729996  585.270020  228.600006  580.729980
2024-10-15 00:00:00+00:00  237.490005  584.900024  232.369995  578.539978
2024-10-16 00:00:00+00:00  232.119995  582.830017  229.839996  578.960022
2024-10-17 00:00:00+00:00  233.850006  586.119995  230.520004  582.159973
2024-10-18 00:00:00+00:00  236.179993  585.390015  234.009995  582.580017
2024-10-21 00:00:00+00:00  236.850006  584.849976  234.449997  580.599976
2024-10-22 00:00:00+00:00  236.220001  584.500000  232.600006  580.380005
2024-10-23 00:00:00+00:00  235.139999  581.710022  227.759995  574.419983
2024-10-24 00:00:00+00:00  230.820007  580.059998  228.410004  576.570007
2024-10-25 00:00:00+00:00  233.220001  584.460022  229.570007  578.080017
2024-10-28 00:00:00+00:00  234.729996  582.710022  232.550003  580.520020
2024-10-29 00:00:00+00:00  234.330002  582.909973  232.320007  578.429993
2024-10-30 00:00:00+00:00  233.470001  583.320007  229.550003  579.289978
2024-10-31 00:00:00+00:00  229.830002  575.630005  226.410004  569.710022

Price                            Open                Volume
Ticker                           AAPL         SPY      AAPL       SPY
Date
2024-09-30 00:00:00+00:00  230.039993  570.419983  54541900  63557400
2024-10-01 00:00:00+00:00  229.520004  573.400024  63285000  72668800
2024-10-02 00:00:00+00:00  225.889999  567.710022  32880600  38097800
2024-10-03 00:00:00+00:00  225.139999  567.359985  34044200  40846500
2024-10-04 00:00:00+00:00  227.899994  572.349976  37245100  42939100
2024-10-07 00:00:00+00:00  224.500000  571.299988  39505400  49964700
2024-10-08 00:00:00+00:00  224.300003  570.419983  31855700  37398700
2024-10-09 00:00:00+00:00  225.229996  573.159973  33591100  37912200
2024-10-10 00:00:00+00:00  227.779999  575.770020  28183500  44138100
2024-10-11 00:00:00+00:00  229.300003  576.049988  31759200  42268000
2024-10-14 00:00:00+00:00  228.699997  581.219971  39882100  36217200
2024-10-15 00:00:00+00:00  233.610001  584.590027  64751400  54203600
2024-10-16 00:00:00+00:00  231.600006  579.780029  34082200  30725400
2024-10-17 00:00:00+00:00  233.429993  585.909973  32993800  34393700
2024-10-18 00:00:00+00:00  236.179993  584.070007  46431500  37416800
2024-10-21 00:00:00+00:00  234.449997  583.849976  36254500  36439000
2024-10-22 00:00:00+00:00  233.889999  581.049988  38846600  34183800
2024-10-23 00:00:00+00:00  234.080002  581.260010  52287000  49314600
2024-10-24 00:00:00+00:00  229.979996  579.979980  31109500  34979900
2024-10-25 00:00:00+00:00  229.740005  581.510010  38802300  47268200
2024-10-28 00:00:00+00:00  233.320007  582.580017  36087100  30174700
2024-10-29 00:00:00+00:00  233.100006  579.849976  35417200  42899700
2024-10-30 00:00:00+00:00  232.610001  581.289978  47070900  41435800
2024-10-31 00:00:00+00:00  229.229996  575.559998  30480749  35001518

In [3]:
df = yf.download(' '.join(sp500), period="10y")
df

[*********************100%***********************]  503 of 503 completed

10 Failed downloads:
['SW']: YFInvalidPeriodError("%ticker%: Period '10y' is invalid, must be one of ['1d', '5d', '1mo', '3mo', '6mo', 'ytd', 'max']")
['KVUE', 'VLTO', 'GEHC']: YFInvalidPeriodError("%ticker%: Period '10y' is invalid, must be one of ['1d', '5d', '1mo', '3mo', '6mo', '1y', '2y', 'ytd', 'max']")
['SOLV', 'GEV']: YFInvalidPeriodError("%ticker%: Period '10y' is invalid, must be one of ['1d', '5d', '1mo', '3mo', '6mo', '1y', 'ytd', 'max']")
['OTIS', 'CEG', 'ABNB', 'CARR']: YFInvalidPeriodError("%ticker%: Period '10y' is invalid, must be one of ['1d', '5d', '1mo', '3mo', '6mo', '1y', '2y', '5y', 'ytd', 'max']")

Price                       Adj Close                                          \
Ticker                              A        AAL        AAPL        ABBV ABNB
Date
2014-10-31 00:00:00+00:00   36.393887  39.179268   23.973495   41.956585  NaN
2014-11-03 00:00:00+00:00   37.588364  39.795147   24.284258   41.817753  NaN
2014-11-04 00:00:00+00:00   36.980907  40.458393   24.106678   41.427670  NaN
2014-11-05 00:00:00+00:00   36.934883  40.032017   24.164398   41.348339  NaN
2014-11-06 00:00:00+00:00   38.076160  40.875298   24.233505   41.460724  NaN
...                               ...        ...         ...         ...  ...
2024-10-25 00:00:00+00:00  130.190002  13.150000  231.410004  187.850006  NaN
2024-10-28 00:00:00+00:00  131.539993  13.600000  233.399994  189.679993  NaN
2024-10-29 00:00:00+00:00  131.229996  13.820000  233.669998  189.449997  NaN
2024-10-30 00:00:00+00:00  131.490005  13.940000  230.100006  201.500000  NaN
2024-10-31 00:00:00+00:00  130.860001  13.455000  227.360107  204.220001  NaN

Price                                                                      \
Ticker                            ABT        ACGL         ACN        ADBE
Date
2014-10-31 00:00:00+00:00   36.026073   18.773333   68.768227   70.120003
2014-11-03 00:00:00+00:00   35.778130   18.799999   68.641075   69.910004
2014-11-04 00:00:00+00:00   36.042606   18.910000   68.793671   71.070000
2014-11-05 00:00:00+00:00   36.083923   18.906668   69.921150   71.370003
2014-11-06 00:00:00+00:00   36.108704   19.026667   70.565430   72.099998
...                               ...         ...         ...         ...
2024-10-25 00:00:00+00:00  114.220001  105.300003  360.799988  483.720001
2024-10-28 00:00:00+00:00  114.070000  105.660004  361.320007  481.040009
2024-10-29 00:00:00+00:00  113.400002  104.800003  363.040009  485.390015
2024-10-30 00:00:00+00:00  114.449997  105.139999  346.570007  486.679993
2024-10-31 00:00:00+00:00  114.080002   99.610001  347.179993  479.232391

Price                                  ...  Volume                             \
Ticker                            ADI  ...     WTW       WY     WYNN      XEL
Date                                   ...
2014-10-31 00:00:00+00:00   40.179710  ...  479916  4841500  1527800  3632900
2014-11-03 00:00:00+00:00   40.260685  ...  504566  3013800  1222900  3243800
2014-11-04 00:00:00+00:00   40.042057  ...  440467  2763400  2088000  3709800
2014-11-05 00:00:00+00:00   40.511711  ...  309965  3056200  2938200  4556000
2014-11-06 00:00:00+00:00   40.665558  ...  398564  2924200  3081700  8182500
...                               ...  ...     ...      ...      ...      ...
2024-10-25 00:00:00+00:00  230.169998  ...  427500  4276900  1098500  7028000
2024-10-28 00:00:00+00:00  230.139999  ...  577400  2884100  1062200  4165700
2024-10-29 00:00:00+00:00  235.229996  ...  547000  7199300  1890200  6475700
2024-10-30 00:00:00+00:00  230.119995  ...  638900  4218100  1337100  2894400
2024-10-31 00:00:00+00:00  223.380005  ...  671455  1482471  1207758  3302862

Price                                                                    \
Ticker                          XOM      XYL      YUM      ZBH     ZBRA
Date
2014-10-31 00:00:00+00:00  17493700  1161000  8379384  1530786   562800
2014-11-03 00:00:00+00:00  13410000   781100  4277047   813082   833000
2014-11-04 00:00:00+00:00  13498500   693800  3248402  1050703  1544000
2014-11-05 00:00:00+00:00  12480000   823700  2750842  1231983  1475600
2014-11-06 00:00:00+00:00  14731400  1218200  3727741   764054   816600
...                             ...      ...      ...      ...      ...
2024-10-25 00:00:00+00:00  10714600   643900   956500  1398200   473400
2024-10-28 00:00:00+00:00  11844500   694000  1318000  1536500   715100
2024-10-29 00:00:00+00:00  14731000   972100  1487200  2153000  1319500
2024-10-30 00:00:00+00:00  12303700  1318500  1414700  3246500   960400
2024-10-31 00:00:00+00:00  12035791  1825046   825700  1239777   438396

Price
Ticker                          ZTS
Date
2014-10-31 00:00:00+00:00   2589500
2014-11-03 00:00:00+00:00   4071300
2014-11-04 00:00:00+00:00   9723700
2014-11-05 00:00:00+00:00  11878900
2014-11-06 00:00:00+00:00   4457100
...                             ...
2024-10-25 00:00:00+00:00   2622900
2024-10-28 00:00:00+00:00   1909700
2024-10-29 00:00:00+00:00   1696000
2024-10-30 00:00:00+00:00   1957800
2024-10-31 00:00:00+00:00   1221866

[2517 rows x 3018 columns]

In [4]:
df['Adj Close'].dropna(how= "any", axis=1).to_csv('sp500.csv')