In [1]:
import pandas as pd

df = pd.read_csv('s&p500.csv')
df = df.set_index('Date')
df

,A,AAL,AAPL,ABBV,ABT,ACGL,ACN,ADBE,ADI,ADM,...,WTW,WY,WYNN,XEL,XOM,XYL,YUM,ZBH,ZBRA,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2014-10-31 00:00:00+00:00,36.393887,39.179268,23.973495,41.956585,36.026073,18.773333,68.768227,70.120003,40.179710,35.525333,...,91.401855,22.913128,162.714340,24.432884,62.614067,32.120022,42.933430,99.750992,73.750000,34.574112
2014-11-03 00:00:00+00:00,37.588364,39.795147,24.284258,41.817753,35.778130,18.799999,68.641075,69.910004,40.260685,35.714283,...,90.792976,23.197344,162.286133,24.637280,61.675262,31.837324,42.772045,99.006737,73.879997,35.163273
2014-11-04 00:00:00+00:00,36.980907,40.458393,24.106678,41.427670,36.042606,18.910000,68.793671,71.070000,40.042057,37.445198,...,90.725319,23.319159,158.646683,24.432884,61.196133,31.748985,43.070908,97.930672,72.779999,36.468380
2014-11-05 00:00:00+00:00,36.934883,40.032017,24.164398,41.348339,36.083923,18.906668,69.921150,71.370003,40.511711,38.027210,...,92.010750,23.265015,153.919647,24.885473,61.552242,32.146519,43.298035,99.526817,73.070000,36.608208
2014-11-06 00:00:00+00:00,38.076160,40.875298,24.233505,41.460724,36.108704,19.026667,70.565430,72.099998,40.665558,37.770222,...,93.950172,23.170267,153.037628,24.126284,62.322708,32.782562,43.692513,98.809441,73.879997,37.018387
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-25 00:00:00+00:00,130.190002,13.150000,231.410004,187.850006,114.220001,105.300003,360.799988,483.720001,230.169998,56.560001,...,290.450012,31.799999,97.989998,64.459999,119.489998,130.419998,133.039993,102.349998,360.089996,180.009995
2024-10-28 00:00:00+00:00,131.539993,13.600000,233.399994,189.679993,114.070000,105.660004,361.320007,481.040009,230.139999,57.240002,...,292.119995,31.950001,98.620003,64.480003,118.900002,130.789993,134.860001,103.599998,363.579987,182.759995
2024-10-29 00:00:00+00:00,131.229996,13.820000,233.669998,189.449997,113.400002,104.800003,363.040009,485.390015,235.229996,56.320000,...,292.179993,30.879999,99.000000,63.340000,117.279999,129.889999,133.970001,103.879997,384.679993,181.270004
2024-10-30 00:00:00+00:00,131.490005,13.940000,230.100006,201.500000,114.449997,105.139999,346.570007,486.679993,230.119995,55.529999,...,293.540009,31.719999,98.489998,63.049999,116.690002,130.220001,133.389999,109.809998,383.890015,182.740005
2024-10-31 00:00:00+00:00,130.860001,13.455000,227.360107,204.220001,114.080002,99.610001,347.179993,479.232391,223.380005,55.439999,...,303.304993,31.415001,96.324997,67.320000,117.089996,123.099998,132.110001,107.440002,381.545013,179.919998

In [3]:
from sklearn.metrics import mutual_info_score
import numpy as np

def calculate_mutual_information(series1, series2, bins=5):
    """
    Calculate the mutual information between two series.
    series1, series2: Pandas Series
    bins: Number of bins for discretization
    """
    # Discretize the series
    data1 = pd.cut(series1, bins=bins, labels=False)
    data2 = pd.cut(series2, bins=bins, labels=False)

    # Compute mutual information
    return mutual_info_score(data1, data2)


def mutual_information_matrix(df, bins=5):
  """
    Calculate the mutual information matrix for all pairs of columns in the DataFrame.
    df: DataFrame with columns as assets and rows as daily log-return values.
    bins: Number of bins for discretization.
  """
  df_tickers = df.columns
  n = len(df.columns)
  mi_matrix = pd.DataFrame(np.zeros((n, n)), index=df_tickers, columns=df_tickers)
  for i in range(n):
    for j in range(i, n):
      mi = calculate_mutual_information(df.iloc[:, i], df.iloc[:, j], bins=bins)
      mi_matrix.iloc[i, j] = mi
      mi_matrix.iloc[j, i] = mi
  return mi_matrix

In [6]:
import numpy as np

T = len(df[df.columns[0]])
S = len(df.columns)

A = np.zeros((S,S))

A = mutual_information_matrix(df[:2])

A.tofile('s&p500_pearson_correlation.csv', sep = ',')

KeyboardInterrupt: