In [13]:
import csv

sp500 = []

with open('sp500/S&P 500 Historical Components & Changes(08-17-2024).csv', 'r') as input:
    reader = csv.reader(input)
    latest = list(reader)[-1][-1]
    # yahoo finance uses - instead of . in symbol names
    sp500 = [name.replace('.', '-') for name in latest.split(',')]

print(len(sp500))

503

In [14]:
import yfinance as yf

df = yf.download("SPY AAPL", period="1mo")
df

[*********************100%***********************]  2 of 2 completed

Price                       Adj Close                   Close              \
Ticker                           AAPL         SPY        AAPL         SPY
Date
2024-09-25 00:00:00+00:00  226.369995  570.039978  226.369995  570.039978
2024-09-26 00:00:00+00:00  227.520004  572.299988  227.520004  572.299988
2024-09-27 00:00:00+00:00  227.789993  571.469971  227.789993  571.469971
2024-09-30 00:00:00+00:00  233.000000  573.760010  233.000000  573.760010
2024-10-01 00:00:00+00:00  226.210007  568.619995  226.210007  568.619995
2024-10-02 00:00:00+00:00  226.779999  568.859985  226.779999  568.859985
2024-10-03 00:00:00+00:00  225.669998  567.820007  225.669998  567.820007
2024-10-04 00:00:00+00:00  226.800003  572.979980  226.800003  572.979980
2024-10-07 00:00:00+00:00  221.690002  567.799988  221.690002  567.799988
2024-10-08 00:00:00+00:00  225.770004  573.169983  225.770004  573.169983
2024-10-09 00:00:00+00:00  229.539993  577.140015  229.539993  577.140015
2024-10-10 00:00:00+00:00  229.039993  576.130005  229.039993  576.130005
2024-10-11 00:00:00+00:00  227.550003  579.580017  227.550003  579.580017
2024-10-14 00:00:00+00:00  231.300003  584.320007  231.300003  584.320007
2024-10-15 00:00:00+00:00  233.850006  579.780029  233.850006  579.780029
2024-10-16 00:00:00+00:00  231.779999  582.299988  231.779999  582.299988
2024-10-17 00:00:00+00:00  232.149994  582.349976  232.149994  582.349976
2024-10-18 00:00:00+00:00  235.000000  584.590027  235.000000  584.590027
2024-10-21 00:00:00+00:00  236.479996  583.630005  236.479996  583.630005
2024-10-22 00:00:00+00:00  235.860001  583.320007  235.860001  583.320007
2024-10-23 00:00:00+00:00  230.759995  577.989990  230.759995  577.989990
2024-10-24 00:00:00+00:00  230.570007  579.239990  230.570007  579.239990

Price                            High                     Low              \
Ticker                           AAPL         SPY        AAPL         SPY
Date
2024-09-25 00:00:00+00:00  227.289993  571.890015  224.020004  568.909973
2024-09-26 00:00:00+00:00  228.500000  574.710022  225.410004  569.900024
2024-09-27 00:00:00+00:00  229.520004  574.219971  227.300003  570.419983
2024-09-30 00:00:00+00:00  233.000000  574.380005  229.649994  568.080017
2024-10-01 00:00:00+00:00  229.649994  574.059998  223.740005  566.000000
2024-10-02 00:00:00+00:00  227.369995  569.900024  223.020004  565.270020
2024-10-03 00:00:00+00:00  226.809998  569.799988  223.320007  565.489990
2024-10-04 00:00:00+00:00  228.000000  573.359985  224.130005  568.099976
2024-10-07 00:00:00+00:00  225.690002  571.960022  221.330002  566.630005
2024-10-08 00:00:00+00:00  225.979996  573.780029  223.250000  569.530029
2024-10-09 00:00:00+00:00  229.750000  577.710022  224.830002  572.549988
2024-10-10 00:00:00+00:00  229.500000  577.580017  227.169998  574.489990
2024-10-11 00:00:00+00:00  229.410004  580.330017  227.339996  575.909973
2024-10-14 00:00:00+00:00  231.729996  585.270020  228.600006  580.729980
2024-10-15 00:00:00+00:00  237.490005  584.900024  232.369995  578.539978
2024-10-16 00:00:00+00:00  232.119995  582.830017  229.839996  578.960022
2024-10-17 00:00:00+00:00  233.850006  586.119995  230.520004  582.159973
2024-10-18 00:00:00+00:00  236.179993  585.390015  234.009995  582.580017
2024-10-21 00:00:00+00:00  236.850006  584.849976  234.449997  580.599976
2024-10-22 00:00:00+00:00  236.220001  584.500000  232.600006  580.380005
2024-10-23 00:00:00+00:00  235.139999  581.710022  227.759995  574.419983
2024-10-24 00:00:00+00:00  230.820007  580.034973  228.410004  576.570007

Price                            Open                Volume
Ticker                           AAPL         SPY      AAPL       SPY
Date
2024-09-25 00:00:00+00:00  224.929993  571.140015  42308700  38428600
2024-09-26 00:00:00+00:00  227.300003  574.380005  36636700  48336000
2024-09-27 00:00:00+00:00  228.460007  573.390015  34026000  42100900
2024-09-30 00:00:00+00:00  230.039993  570.419983  54541900  63557400
2024-10-01 00:00:00+00:00  229.520004  573.400024  63285000  72668800
2024-10-02 00:00:00+00:00  225.889999  567.710022  32880600  38097800
2024-10-03 00:00:00+00:00  225.139999  567.359985  34044200  40846500
2024-10-04 00:00:00+00:00  227.899994  572.349976  37245100  42939100
2024-10-07 00:00:00+00:00  224.500000  571.299988  39505400  49964700
2024-10-08 00:00:00+00:00  224.300003  570.419983  31855700  37398700
2024-10-09 00:00:00+00:00  225.229996  573.159973  33591100  37912200
2024-10-10 00:00:00+00:00  227.779999  575.770020  28183500  44138100
2024-10-11 00:00:00+00:00  229.300003  576.049988  31759200  42268000
2024-10-14 00:00:00+00:00  228.699997  581.219971  39882100  36217200
2024-10-15 00:00:00+00:00  233.610001  584.590027  64751400  54203600
2024-10-16 00:00:00+00:00  231.600006  579.780029  34082200  30725400
2024-10-17 00:00:00+00:00  233.429993  585.909973  32993800  34393700
2024-10-18 00:00:00+00:00  236.179993  584.070007  46431500  37416800
2024-10-21 00:00:00+00:00  234.449997  583.849976  36254500  36439000
2024-10-22 00:00:00+00:00  233.889999  581.049988  38846600  34183800
2024-10-23 00:00:00+00:00  234.080002  581.260010  52287000  49314600
2024-10-24 00:00:00+00:00  229.917007  579.979980  29945097  34813389

In [15]:
df = yf.download(' '.join(sp500), period="10y")
df

[*********************100%***********************]  503 of 503 completed

10 Failed downloads:
['GEHC', 'VLTO', 'KVUE']: YFInvalidPeriodError("%ticker%: Period '10y' is invalid, must be one of ['1d', '5d', '1mo', '3mo', '6mo', '1y', '2y', 'ytd', 'max']")
['CEG', 'CARR', 'OTIS', 'ABNB']: YFInvalidPeriodError("%ticker%: Period '10y' is invalid, must be one of ['1d', '5d', '1mo', '3mo', '6mo', '1y', '2y', '5y', 'ytd', 'max']")
['GEV', 'SOLV']: YFInvalidPeriodError("%ticker%: Period '10y' is invalid, must be one of ['1d', '5d', '1mo', '3mo', '6mo', '1y', 'ytd', 'max']")
['SW']: YFInvalidPeriodError("%ticker%: Period '10y' is invalid, must be one of ['1d', '5d', '1mo', '3mo', '6mo', 'ytd', 'max']")

Price                       Adj Close                                          \
Ticker                              A        AAL        AAPL        ABBV ABNB
Date
2014-10-27 00:00:00+00:00   35.544605  37.720184   23.331984   39.992973  NaN
2014-10-28 00:00:00+00:00   35.985706  38.032078   23.693810   40.283882  NaN
2014-10-29 00:00:00+00:00   35.880356  37.748539   23.826988   39.655781  NaN
2014-10-30 00:00:00+00:00   35.761864  38.184391   23.747078   40.449177  NaN
2014-10-31 00:00:00+00:00   36.393875  39.179272   23.973497   41.956593  NaN
...                               ...        ...         ...         ...  ...
2024-10-18 00:00:00+00:00  138.830002  13.090000  235.000000  188.860001  NaN
2024-10-21 00:00:00+00:00  136.759995  12.970000  236.479996  186.539993  NaN
2024-10-22 00:00:00+00:00  133.460007  12.960000  235.860001  188.759995  NaN
2024-10-23 00:00:00+00:00  133.029999  12.830000  230.759995  187.880005  NaN
2024-10-24 00:00:00+00:00  130.690002  12.780000  230.570007  189.649994  NaN

Price                                                                      \
Ticker                            ABT        ACGL         ACN        ADBE
Date
2014-10-27 00:00:00+00:00   34.910320   18.703333   66.987968   67.029999
2014-10-28 00:00:00+00:00   35.125217   18.756666   67.369476   68.370003
2014-10-29 00:00:00+00:00   35.323566   18.743334   67.437271   67.930000
2014-10-30 00:00:00+00:00   35.943420   18.723333   68.344368   68.570000
2014-10-31 00:00:00+00:00   36.026051   18.773333   68.768234   70.120003
...                               ...         ...         ...         ...
2024-10-18 00:00:00+00:00  119.389999  108.529999  376.859985  494.899994
2024-10-21 00:00:00+00:00  116.989998  108.500000  376.029999  497.709991
2024-10-22 00:00:00+00:00  116.120003  107.790001  371.790009  493.109985
2024-10-23 00:00:00+00:00  117.010002  107.000000  370.630005  485.029999
2024-10-24 00:00:00+00:00  116.540001  107.040001  364.230011  482.869995

Price                                  ...  Volume                             \
Ticker                            ADI  ...     WTW       WY     WYNN      XEL
Date                                   ...
2014-10-27 00:00:00+00:00   37.750469  ...  178784  2514300  2002400  2921100
2014-10-28 00:00:00+00:00   38.050076  ...  261268  2516900  1661400  2931200
2014-10-29 00:00:00+00:00   38.309196  ...  683162  4234700  2563700  2950100
2014-10-30 00:00:00+00:00   38.058174  ...  308115  4727000  1176100  5013100
2014-10-31 00:00:00+00:00   40.179714  ...  479916  4841500  1527800  3632900
...                               ...  ...     ...      ...      ...      ...
2024-10-18 00:00:00+00:00  228.330002  ...  437800  2538600  2269800  3651800
2024-10-21 00:00:00+00:00  225.669998  ...  382400  2221800  1674100  2178700
2024-10-22 00:00:00+00:00  224.619995  ...  507000  4820800  1403700  2243900
2024-10-23 00:00:00+00:00  226.850006  ...  545300  3412300  1683100  2338200
2024-10-24 00:00:00+00:00  229.679993  ...  395498  1869273  1898048  4910581

Price                                                                   \
Ticker                          XOM      XYL      YUM      ZBH    ZBRA
Date
2014-10-27 00:00:00+00:00  11387700  1397900  1974385   591941  331700
2014-10-28 00:00:00+00:00  12564100  1857800  2466243  1752236  331100
2014-10-29 00:00:00+00:00  12409100   907400  3372758  1400800  315400
2014-10-30 00:00:00+00:00   9767900   658400  2917483   811022  455400
2014-10-31 00:00:00+00:00  17493700  1161000  8379384  1530786  562800
...                             ...      ...      ...      ...     ...
2024-10-18 00:00:00+00:00  12898600  1018200  1243600  1081600  222100
2024-10-21 00:00:00+00:00  10177800   656800  1294900   936400  232900
2024-10-22 00:00:00+00:00   9201400   927600   941700  1430900  188000
2024-10-23 00:00:00+00:00   8320300   724700  1605100   744300  224100
2024-10-24 00:00:00+00:00   6791100   558147  1008415   501084  376332

Price
Ticker                         ZTS
Date
2014-10-27 00:00:00+00:00  2511400
2014-10-28 00:00:00+00:00  1533400
2014-10-29 00:00:00+00:00  2269900
2014-10-30 00:00:00+00:00  2137900
2014-10-31 00:00:00+00:00  2589500
...                            ...
2024-10-18 00:00:00+00:00  1576400
2024-10-21 00:00:00+00:00   959500
2024-10-22 00:00:00+00:00  1441900
2024-10-23 00:00:00+00:00  1339500
2024-10-24 00:00:00+00:00  4140664

[2516 rows x 3018 columns]

In [25]:
df['Adj Close'].dropna(how= "all", axis=1).to_csv('s&p500.csv')